# Generated by Django 5.2.7 on 2026-01-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_country_parcel_delivery_city_parcel_pickup_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Price (OMR)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='thawani_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thawani Session ID'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_city_parcels', to='core.city', verbose_name='Delivery City'),
        ),
    ]
