# Generated by Django 5.2.7 on 2026-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parcel_payment_status_parcel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='governate',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='governate',
            name='name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='governate',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Name (English)'),
        ),
    ]
