# Generated by Django 5.2.7 on 2026-01-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_city_name_remove_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='governate',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='governate',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
    ]
