# Generated by Django 5.2.7 on 2026-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_city_name_ar_alter_city_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/', verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration Number')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT Number')),
            ],
            options={
                'verbose_name': 'Platform Profile',
                'verbose_name_plural': 'Platform Profile',
            },
        ),
    ]
