# Generated by Django 5.2.7 on 2026-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_platformprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='privacy_policy',
            field=models.TextField(blank=True, verbose_name='Privacy Policy'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='terms_conditions',
            field=models.TextField(blank=True, verbose_name='Terms and Conditions'),
        ),
    ]
