# Generated by Django 5.2.7 on 2026-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_address_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, help_text='Permanent or temporary access token from Meta Business.', verbose_name='WhatsApp Access Token'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='whatsapp_business_phone_number_id',
            field=models.CharField(blank=True, help_text='The Phone Number ID from WhatsApp API setup.', max_length=100, verbose_name='WhatsApp Phone Number ID'),
        ),
    ]
