# Generated by Django 5.2.7 on 2026-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platformprofile_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='whatsapp_app_secret',
            field=models.CharField(blank=True, help_text='App Secret or Verify Token for Webhooks.', max_length=255, verbose_name='WhatsApp App Secret (Security Key)'),
        ),
    ]
