# Generated by Django 5.2.7 on 2026-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_platformprofile_whatsapp_app_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprofile',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, help_text='Your Wablas API Token.', verbose_name='Wablas API Token'),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='whatsapp_app_secret',
            field=models.CharField(blank=True, help_text='Your Wablas API Secret Key (if required).', max_length=255, verbose_name='Wablas Secret Key'),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='whatsapp_business_phone_number_id',
            field=models.CharField(blank=True, default='https://deu.wablas.com', help_text='The Wablas API domain (e.g., https://deu.wablas.com).', max_length=100, verbose_name='Wablas Domain'),
        ),
    ]
