# Generated by Django 5.2.7 on 2026-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_platformprofile_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='enable_payment',
            field=models.BooleanField(default=True, help_text='Toggle to enable or disable payments on the platform.', verbose_name='Enable Payment'),
        ),
    ]
