# Generated by Django 5.2.7 on 2026-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_platformprofile_enable_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('profile_update', 'Profile Update'), ('password_reset', 'Password Reset'), ('registration', 'Registration')], default='profile_update', max_length=20),
        ),
    ]
