# Generated by Django 5.2.7 on 2026-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('role_en', models.CharField(max_length=100, verbose_name='Role (English)')),
                ('role_ar', models.CharField(max_length=100, verbose_name='Role (Arabic)')),
                ('content_en', models.TextField(verbose_name='Testimony (English)')),
                ('content_ar', models.TextField(verbose_name='Testimony (Arabic)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
