# Generated by Django 5.2.7 on 2026-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text='e.g. +968', max_length=10, verbose_name='Phone Code'),
        ),
    ]
