# Generated by Django 5.2.7 on 2026-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Car Plate Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='License Back Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='License Front Image'),
        ),
    ]
