# Generated by Django 5.2.7 on 2026-01-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformprofile',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='platformprofile',
            name='terms_conditions',
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='privacy_policy_ar',
            field=models.TextField(blank=True, verbose_name='Privacy Policy (Arabic)'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='privacy_policy_en',
            field=models.TextField(blank=True, verbose_name='Privacy Policy (English)'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='terms_conditions_ar',
            field=models.TextField(blank=True, verbose_name='Terms and Conditions (Arabic)'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='terms_conditions_en',
            field=models.TextField(blank=True, verbose_name='Terms and Conditions (English)'),
        ),
    ]
