# Generated by Django 5.2.7 on 2026-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pricingrule_parcel_delivery_lat_parcel_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='auto_mark_paid',
            field=models.BooleanField(default=False, help_text="If enabled, newly created parcels will automatically be marked as 'Paid' for testing.", verbose_name='Test Mode: Auto-Paid'),
        ),
    ]
