# Generated by Django 5.2.7 on 2026-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_platformprofile_auto_mark_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='admin_panel_logo',
            field=models.ImageField(blank=True, help_text='Logo for the Admin Panel (top left).', null=True, upload_to='platform_logos/', verbose_name='Admin Panel Logo'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a favicon (e.g., .ico or .png)', null=True, upload_to='platform_logos/', verbose_name='Favicon'),
        ),
    ]
