# Generated by Django 5.2.7 on 2026-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_platformprofile_admin_panel_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number'),
        ),
    ]
