# Generated by Django 5.2.7 on 2026-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profile_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driver_grade',
            field=models.CharField(choices=[('none', 'No Grade'), ('bronze_3', 'Bronze III'), ('bronze_2', 'Bronze II'), ('bronze_1', 'Bronze I'), ('silver', 'Silver'), ('gold', 'Gold')], default='none', max_length=20, verbose_name='Driver Grade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended by Shippers'),
        ),
    ]
