# Generated by Django 5.2.7 on 2026-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profile_driver_grade_profile_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='accepting_shipments',
            field=models.BooleanField(default=True, help_text='Toggle to allow or stop receiving new parcel shipments.', verbose_name='Accepting Shipments'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='maintenance_message_ar',
            field=models.TextField(blank=True, help_text='Message to show when shipments are stopped.', verbose_name='Maintenance Message (Arabic)'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='maintenance_message_en',
            field=models.TextField(blank=True, help_text='Message to show when shipments are stopped.', verbose_name='Maintenance Message (English)'),
        ),
    ]
