# Generated by Django 5.2.7 on 2026-02-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_platformprofile_auto_ban_on_rejections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprofile',
            name='ticker_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for the live activity ticker (e.g. #FFFFFF or white).', max_length=20, verbose_name='Ticker Background Color'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='ticker_limit',
            field=models.PositiveIntegerField(default=10, help_text='Number of recent shipments to show in the live activity ticker.', verbose_name='Ticker Shipment Limit'),
        ),
        migrations.AddField(
            model_name='platformprofile',
            name='ticker_text_color',
            field=models.CharField(default='#1A1A1D', help_text='Text color for the live activity ticker.', max_length=20, verbose_name='Ticker Text Color'),
        ),
    ]
